# FastAgent Configuration File

# Default Model Configuration:
#
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku".
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

#default_model: haiku
#default_model: deepseek-r1:1.5b

generic:
    base_url: "http://localhost:11434/v1"

# Logging and Console Configuration:
logger:
    level: "info"
    type: "file"
    #level: "debug" | "info" | "warning" | "error"
    # type: "none" | "console" | "file" | "http"
    # path: "/path/to/logfile.jsonl"

    # Switch the progress display on or off
    progress_display: false

    # Show chat User/Assistant messages on the console
    show_chat: true
    # Show tool calls on the console
    show_tools: false
    # Truncate long tool responses on the console
    truncate_tools: false

mcp:
    servers:
        demo-server:
            transport: "http"
            # url to connect
            url: "http://localhost:9090/mcp"
